-- STUID 103585238
-- NAME Huynh Qui Dang

-- TASK 1 ERD TO RELATIONAL SCHEMA

-- SUBJECT (SubjCode, Description)
-- PRIMARY KEY (SubjCode)

-- STUDENT (StudentID, Surname, GivenName, Gender)
-- PRIMARY KEY (StudentID)

-- TEACHER (StaffID, Surname, GivenName)
-- PRIMARY KEY (StaffID)

-- SUBJECTOFERING (SubjCode, StaffID, Year, Semester, Fee)
-- PRIMARY KEY (SubjCode, StaffID, Year, Semester)
-- FOREIGN KEY (Subjcode) REFERENCES Subject
-- FOREIGN KEY (StaffID) REFERENCES Teacher 

-- ENROLMENT (StudentID, SubjCode, Year, Semester, DateEnrolled, Grade)
-- PRIMARY KEY (StudentID, SubjCode, Year, Semester) 
-- FOREIGN KEY (StudentID) REFERENCES Student
-- FOREIGN KEY (SubjCode, Year, Semester) REFERENCES SubjectOffering 

--TASK 2 
USE BQCHALLENGERESIT;
DROP TABLE ENROLMENT, SUBJECTOFFERING, TEACHER, STUDENT, SUBJECT;

CREATE TABLE SUBJECT (
    SUBJCODE NVARCHAR(100)
    ,Descrption NVARCHAR(500)
    ,PRIMARY KEY (SUBJCODE)
);

CREATE TABLE STUDENT (
    STUDENTID NVARCHAR(10)
    ,SURNAME NVARCHAR(100) NOT NULL
    ,GIVENNAME NVARCHAR(100) NOT NULL
    ,GENDER NVARCHAR(1)
    ,PRIMARY KEY (STUDENTID)
    ,CONSTRAINT CHK_GENDER CHECK (GENDER IN('M', 'F', 'I') )
)

CREATE TABLE TEACHER (
    STAFFID INT
    ,SURNAME NVARCHAR(100) NOT NULL
    ,GIVENNAME NVARCHAR(100) NOT NULL
    ,PRIMARY KEY (STAFFID)
    ,CONSTRAINT CHK_TEACHER_STAFFID CHECK( LEN(STAFFID)=8 ) 
)

CREATE TABLE SUBJECTOFERRING (
    STAFFID INT
    ,SUBJCODE NVARCHAR(100) 
    ,YEAR INT
    ,SEMESTER INT 
    ,FEE MONEY NOT NULL
    ,PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
    ,FOREIGN KEY (STAFFID) REFERENCES TEACHER
    ,CONSTRAINT CHK_SUBJECTOFFERING_YEAR CHECK( LEN(YEAR)=4 )     
    ,CONSTRAINT CHK_SUBJECTOFFERING_SEM CHECK( SEMESTER IN(1,2 ) )
    ,CONSTRAINT CHK_SUBJECTOFFERING_FEE CHECK( FEE >0)
);

CREATE TABLE ENROLMENT (
    STUDENTID NVARCHAR(10)
    ,SUBJCODE NVARCHAR(100)
    ,YEAR INT 
    ,SEMESTER INT 
    ,GRADE NVARCHAR(2)
    ,DATEENROLLED DATE
    ,PRIMARY KEY (STUDENTID, SUBJCODE, YEAR, SEMESTER)
    ,FOREIGN KEY (STUDENTID) REFERENCES STUDENT
    ,FOREIGN KEY (SUBJCODE, YEAR, SEMESTER) REFERENCES SUBJECTOFERRING
    ,CONSTRAINT CHK_ENROLMENT_YEAR CHECK( LEN(YEAR)=4 )
    ,CONSTRAINT CHK_ENROLMENT_SEM CHECK( SEMESTER IN (1,2) )
    ,CONSTRAINT CHK_ENROLMENT_GRADE CHECK(GRADE IN ('N', 'P', 'C', 'D', 'HD') )
)